---
- name: Add Ansible User
  ansible.builtin.user:
    name: ansible
    comment: Ansible User
    state: present
    password: !
    system: true
    create_home: true
    home: /home/ansible
    shell: /bin/bash
    password_lock: true

- name: Configure SSH (Including forcing public key for Ansible User)
  ansible.builtin.template:
    src: ansible/sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: Restart sshd

- name: Allow Ansible User passwordless sudo
  ansible.builtin.template:
    src: ansible/sudo.j2
    dest: /etc/sudoers.d/01-ansible

- name: Set Authorized Key
  ansible.builtin.authorized_key:
    exclusive: true
    state: present
    user: ansible
    key: "{{ user_management_ansible_auth_key }}"
    path: /home/ansible/.ssh/authorized_keys
