---
- name: Stop user processes
  ansible.builtin.shell: "pgrep -u {{ item }} && pkill -9 -u {{ item }} || true"
  with_items: "{{ user_management_unauthorized_users }}"
  tags:
    - auth_accounts
    - auth_deletion
  register: stop_user_result
  changed_when: stop_user_result.stdout != ""
  ignore_errors: "{{ ansible_check_mode }}"

- name: Delete accounts
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
    remove: yes
  with_items: "{{ user_management_unauthorized_users }}"
  tags:
    - auth_accounts
    - auth_deletion
