---
- name: Configure sshd
  ansible.builtin.template:
    src: sshd/sshd_config.j2
    dest: /etc/ssh/sshd_config
    lstrip_blocks: true
    trim_blocks: true
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  notify: Restart sshd
